### ISSUE TITLE
Same for mongodb ?

### ISSUE THREAD

**Issue by pesseyjulien** [khanakiaphp/mamp_extensions#1]
Hi,

Sorry to bother you. But I'm running on an issue with the mongodb extension, MAMP does not support the mac arm chipset yet. So I was wondering if you could provide a precompiled mongodb extension ?

Best,
Julien Pessey

**Comment by khanakia** [comment]
@pesseyjulien 
Here you go https://github.com/khanakiaphp/mamp_extensions/blob/master/php7.4.2/mongodb.so

**Comment by pesseyjulien** [comment]
Not working :/ 

Getting the following error : 

code signature in (/Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so) not valid for use in process using Library Validation: library load disallowed by system policy)

I guess it has to be build on the machine !

Thanks for the try anyway,
Julien

**Comment by khanakia** [comment]
@pesseyjulien 
No that is something else. Usually it works on all the machine. It's a permission issue.
Check this link please https://support.blackfire.io/en/articles/3669492-issues-with-macos-catalina

**Comment by khanakia** [comment]
@pesseyjulien 
try these commands
1. With your terminal, go to the directory where you installed blackfire.so;
`cd /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902`
2. Run `xattr mongodb.so`
It should display com.apple.quarantine;
3. Run `xattr -d com.apple.quarantine mongodb.so`

**Comment by pesseyjulien** [comment]
Thanks for the help !

I dont have the error anymore but now I got an error with the snappy lib :

```
[05-Feb-2021 21:52:28 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'mongodb.so' (tried: /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so (dlopen(/Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so, 9): Library not loaded: /usr/local/opt/snappy/lib/libsnappy.1.dylib
  Referenced from: /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so
  Reason: image not found), /Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so (dlopen(/Applications/MAMP/bin/php/php7.4.2/lib/php/extensions/no-debug-non-zts-20190902/mongodb.so.so, 9): image not found)) in Unknown on line 0
```

Installed it with brew but still nothing :/

This mongodb php extension is always a pain to install..

**Comment by khanakia** [comment]
@pesseyjulien you have wrong filename `mongodb.so.so` please double check the filename

**Comment by pesseyjulien** [comment]
No it's correct (see screenshot), I don't know why it says 'mongodb.so.so' in the error..

![Capture d’écran 2021-02-06 à 09 42 37](https://user-images.githubusercontent.com/10850944/107113525-c0c12f80-685f-11eb-962c-aeb491fbf58a.jpg)

**Comment by khanakia** [comment]
@pesseyjulien 

Try this
```
brew install snappy
 cd /usr/local/lib/
 ln -s /usr/local/Cellar/snappy/1.1.1/lib/libsnappy.1.dylib
 ln -s /usr/local/Cellar/snappy/1.1.1/lib/libsnappy.a
 ln -s /usr/local/Cellar/snappy/1.1.1/lib/libsnappy.dylib

```

**Comment by pesseyjulien** [comment]
Not better :/

**Comment by khanakia** [comment]
Do you get the same error `/usr/local/opt/snappy/lib/libsnappy.1.dylib` not loaded ? If yes then it seems snappy is still installed fully.

**Comment by pesseyjulien** [comment]
Yeah still the same error.

I installed snappy using brew :

![Capture d’écran 2021-02-08 à 10 17 48](https://user-images.githubusercontent.com/10850944/107199583-ecc2e900-69f6-11eb-98bc-12a8d399046e.jpg)

And then I created the symlink like you told me :

![Capture d’écran 2021-02-08 à 10 18 37](https://user-images.githubusercontent.com/10850944/107199697-06643080-69f7-11eb-9a91-02ef8b124bc8.jpg)

What could be missing ?

**Comment by khanakia** [comment]
What mongo version are you using `mongo --version` i am using `MongoDB shell version v4.2.1` and it's working. So it could be related to the mongo version error but i cannot make sure.

**Comment by pesseyjulien** [comment]
Hi,

I managed to install it using pecl install and the '-a' option

Thanks a lot for your help and trying so hard :) 

Best,
Julien
